encoding: utf-8

#url: http://ioioj5.github.io
url: http://www.woniu.me
name: 蜗牛的部落格

markdown: kramdown

# code highlighting
highlighter: rouge

# standard jekyll configuration options
exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

#domain: http://ioioj5.github.io
domain: http://www.woniu.me
author: __都非拉得
email: peng_du2007@qq.com

theme: jekyll-theme-slate